changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - pre-commit-ci
  categories:
    # All PRs tagged as "breaking"
    - title: Breaking Changes
      labels:
        - breaking
    # All PRs tagged as "feature"
    - title: New Features
      labels:
        - feature
    # All PRs tagged as "bug"
    - title: Bug Fixes
      labels:
        - bug
    # All PRs not tagged as the above or below
    - title: Internal Changes
      labels:
        - internal
      exclude:
        labels:
          - dependencies
          - documentation
    # All PRs tagged as documentation
    - title: Documentation
      labels:
        - documentation
    # All PRs tagged "dependencies"
    - title: Dependencies
      labels:
        - dependencies
    # All PRs not tagged as the above
    - title: Other Changes
      labels:
        - "*"
