name: Bug Report
description: Report errors or unexpected results.
labels: ["bug"]
assignees:
  - gpauloski
body:
  - type: textarea
    id: install
    attributes:
      label: How did you install the package and dependencies?
      description: >
        E.g., install via pip, install from source, etc. Include versions of
        all code used. **Note:** this will be rendered as console text
        automatically.
      placeholder: |
        $ pip install -e .
        ...
      render: console
    validations:
      required: true

  - type: textarea
    id: freeform
    attributes:
      label: Describe the problem.
      description: >
        Please provide sample code and directions for reproducing
        your problem and what you expected to happen.
    validations:
      required: true
